-- LOCORA PART 4/6: reviews + chats + messages + auto-notify. Run parts 1 to 6 in order.
create table if not exists public.reviews ( id uuid primary key default gen_random_uuid(), target_id uuid not null references public.profiles (id) on delete cascade, author uuid not null references public.profiles (id) on delete cascade, rating integer not null check (rating between 1 and 5), text text not null default '', deal_type text not null default 'product' check (deal_type in ('product', 'service')), created_at timestamptz not null default now() );
create index if not exists reviews_target_idx on public.reviews (target_id, created_at desc);
alter table public.reviews enable row level security;
drop policy if exists "reviews are public" on public.reviews;
create policy "reviews are public" on public.reviews for select using (true);
drop policy if exists "users write own reviews" on public.reviews;
create policy "users write own reviews" on public.reviews for insert with check (auth.uid() = author);
drop policy if exists "authors edit own reviews" on public.reviews;
create policy "authors edit own reviews" on public.reviews for update using (auth.uid() = author or public.is_admin());
drop policy if exists "authors delete own reviews" on public.reviews;
create policy "authors delete own reviews" on public.reviews for delete using (auth.uid() = author or public.is_admin());
create table if not exists public.conversations ( id text primary key, participants uuid[] not null check (array_length(participants, 1) = 2), subject jsonb not null, updated_at timestamptz not null default now(), unread_for uuid[] not null default '{}' );
create index if not exists conversations_participant_idx on public.conversations using gin (participants);
alter table public.conversations enable row level security;
drop policy if exists "participants see own threads" on public.conversations;
create policy "participants see own threads" on public.conversations for select using (auth.uid() = any (participants));
drop policy if exists "participants create threads" on public.conversations;
create policy "participants create threads" on public.conversations for insert with check (auth.uid() = any (participants));
drop policy if exists "participants update threads" on public.conversations;
create policy "participants update threads" on public.conversations for update using (auth.uid() = any (participants));
create table if not exists public.messages ( id uuid primary key default gen_random_uuid(), conversation_id text not null references public.conversations (id) on delete cascade, sender_id uuid not null references public.profiles (id) on delete cascade, text text not null default '', at timestamptz not null default now(), kind text not null default 'text' check (kind in ('text', 'offer', 'system')), offer jsonb );
create index if not exists messages_thread_idx on public.messages (conversation_id, at);
alter table public.messages enable row level security;
drop policy if exists "participants read messages" on public.messages;
create policy "participants read messages" on public.messages for select using ( exists ( select 1 from public.conversations c where c.id = conversation_id and auth.uid() = any (c.participants) ) );
drop policy if exists "participants send messages" on public.messages;
create policy "participants send messages" on public.messages for insert with check ( sender_id = auth.uid() and exists ( select 1 from public.conversations c where c.id = conversation_id and auth.uid() = any (c.participants) ) );
create or replace function public.handle_new_message() returns trigger language plpgsql security definer set search_path = public as $$ declare others uuid[]; begin update public.conversations set updated_at = new.at where id = new.conversation_id; select array_remove(participants, new.sender_id) into others from public.conversations where id = new.conversation_id; if coalesce(array_length(others, 1), 0) > 0 then insert into public.notifications (user_id, kind, title, body, href) select u, 'message', 'New message', left(coalesce(nullif(new.text, ''), 'You received an offer'), 90), '/chat' from unnest(others) as u; end if; return new; end; $$;
drop trigger if exists on_message_created on public.messages;
create trigger on_message_created after insert on public.messages for each row execute function public.handle_new_message();
