-- LOCORA PART 5/6: requests + reports + notifications + favourites. Run parts 1 to 6 in order.
create table if not exists public.buy_requests ( id uuid primary key default gen_random_uuid(), buyer_id uuid not null references public.profiles (id) on delete cascade, text text not null, category text not null default 'general', area text not null default 'viman', budget_max integer, need_by text not null default 'flexible' check (need_by in ('today', 'tomorrow', 'this-week', 'weekend', 'flexible')), status text not null default 'open' check (status in ('open', 'fulfilled')), created_at timestamptz not null default now(), watching boolean not null default false, matches jsonb not null default '[]' );
create index if not exists buy_requests_feed_idx on public.buy_requests (status, created_at desc);
create index if not exists buy_requests_area_idx on public.buy_requests (area);
alter table public.buy_requests enable row level security;
drop policy if exists "requests are public" on public.buy_requests;
create policy "requests are public" on public.buy_requests for select using (true);
drop policy if exists "users post own requests" on public.buy_requests;
create policy "users post own requests" on public.buy_requests for insert with check (auth.uid() = buyer_id);
drop policy if exists "owners update own requests" on public.buy_requests;
create policy "owners update own requests" on public.buy_requests for update using (auth.uid() = buyer_id or public.is_admin());
drop policy if exists "owners delete own requests" on public.buy_requests;
create policy "owners delete own requests" on public.buy_requests for delete using (auth.uid() = buyer_id or public.is_admin());
create table if not exists public.reports ( id uuid primary key default gen_random_uuid(), target_type text not null check (target_type in ('product', 'service', 'user', 'chat')), target_id text not null, target_label text not null default '', reason text not null, details text not null default '', by uuid not null references public.profiles (id) on delete cascade, created_at timestamptz not null default now(), status text not null default 'open' check (status in ('open', 'reviewing', 'resolved')) );
create index if not exists reports_status_idx on public.reports (status, created_at desc);
alter table public.reports enable row level security;
drop policy if exists "admins and reporters see reports" on public.reports;
create policy "admins and reporters see reports" on public.reports for select using (public.is_admin() or auth.uid() = by);
drop policy if exists "authenticated users report" on public.reports;
create policy "authenticated users report" on public.reports for insert with check (auth.uid() = by);
drop policy if exists "admins update reports" on public.reports;
create policy "admins update reports" on public.reports for update using (public.is_admin());
create table if not exists public.notifications ( id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles (id) on delete cascade, kind text not null default 'system' check (kind in ('match', 'message', 'price', 'system', 'review')), title text not null, body text not null default '', at timestamptz not null default now(), read boolean not null default false, href text );
create index if not exists notifications_user_idx on public.notifications (user_id, at desc);
alter table public.notifications enable row level security;
drop policy if exists "users see own notifications" on public.notifications;
create policy "users see own notifications" on public.notifications for select using (auth.uid() = user_id);
drop policy if exists "users update own notifications" on public.notifications;
create policy "users update own notifications" on public.notifications for update using (auth.uid() = user_id);
drop policy if exists "users delete own notifications" on public.notifications;
create policy "users delete own notifications" on public.notifications for delete using (auth.uid() = user_id);
create table if not exists public.favorites ( user_id uuid not null references public.profiles (id) on delete cascade, product_id uuid not null references public.products (id) on delete cascade, created_at timestamptz not null default now(), primary key (user_id, product_id) );
alter table public.favorites enable row level security;
drop policy if exists "users see own favorites" on public.favorites;
create policy "users see own favorites" on public.favorites for select using (auth.uid() = user_id);
drop policy if exists "users add own favorites" on public.favorites;
create policy "users add own favorites" on public.favorites for insert with check (auth.uid() = user_id);
drop policy if exists "users remove own favorites" on public.favorites;
create policy "users remove own favorites" on public.favorites for delete using (auth.uid() = user_id);
